services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-gds
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*"
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 512m
      NEO4J_server_memory_pagecache_size: 512m
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/plugins:/plugins